spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring-labs
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql